version: '2'
services:
    db:
        image: mongo
        command: "--smallfiles --logpath=/dev/null"
    web:
        build: ..
        ports:
            - "3000:3000"
        depends_on:
            - db
        links:
            - db
        environment:
            NODE_ENV: docker
        command:
            npm run demo
